### ISSUE TITLE
Cannot create instance of AmazonQLDBClient

### ISSUE THREAD

**Issue by honey-hoper** [awslabs/amazon-qldb-driver-dotnet#22]
Hello team I've installed Amazon.QLDB.Driver package and there is not AmazonQLDBClient. 
Is it removed? Or do I have to install some other package?
If it's removed then how can I perform operations on ledgers?

**Comment by yoroto** [comment]
Hi @honey-hoper 

The [AmazonQLDBClient](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/QLDB/TQLDBClient.html) is part of the AWS SDK for .Net, rather than the QLDB Driver for .Net. Most of the APIs concerning ledgers are in the AWS SDK, and the Driver mainly handles the communication between your application with existing ledgers, rather than managing ledgers.

**Comment by honey-hoper** [comment]
Thanks!
