### ISSUE TITLE
Unable to use Amazon.QLDB.Driver with other AWSSDK.* packages

### ISSUE THREAD

**Issue by stage88** [awslabs/amazon-qldb-driver-dotnet#71]
Hi, 

I am unable to install the latest version Amazon.QLDB.Driver due to a conflict with AWSSDK.Core (>= 3.5.2.9 && < 3.6.0).

Steps to replicate:

1. Create a new .Net Class Library project
2. Add (for example) latest version of AWSSDK.XRay nuget package
3. Add latest version of Amazon.QLDB.Driver nuget package

You'll get a failure from Package Manager:
```
Restoring packages for D:\source\repos\ClassLibrary2\ClassLibrary2\ClassLibrary2.csproj...
NU1107: Version conflict detected for AWSSDK.Core. Install/reference AWSSDK.Core 3.7.0.10 directly to project ClassLibrary2 to resolve this issue. 
 ClassLibrary2 -> AWSSDK.XRay 3.7.0.9 -> AWSSDK.Core (>= 3.7.0.10 && < 3.8.0) 
 ClassLibrary2 -> Amazon.QLDB.Driver 1.2.0 -> AWSSDK.QLDBSession 3.5.2 -> AWSSDK.Core (>= 3.5.2.9 && < 3.6.0).
Package restore failed. Rolling back package changes for 'ClassLibrary2'.
Time Elapsed: 00:00:00.4196905
========== Finished ==========
```

I think AWSSDK.QLDBSession might need to be bumped up to a higher version. Happy to crate a PR....

**Comment by stage88** [comment]
Installing AWSSDK.Core 3.7.0.10 directly fixes the problem, not sure if that has unintended consequences on AWSSDK.QLDBSession

**Comment by simonz-bq** [comment]
Hi @stage88 

Installing SDKCore 3.7 directly is unlikely to cause problems as it follows semantic versioning. The SDK dependencies are automatically generated and we aim to only need a minimum version for the driver as it's a library. 

We'll look into why the SDK specifies a maximum minor version difference.

**Comment by simonz-bq** [comment]
@stage88 

As a follow-up after some investigation, these are the things I found.

Nuget automatically resolves to the minimum required version for transitive dependencies. There is a long-running open feature for a setting to have Nuget resolve to the newest version that follows semantic versioning rules: https://github.com/NuGet/Home/issues/5553

The AWS SDK team is also aware of the maximum versioning causing issues with people's builds. This being fixed won't resolve the immediate issue here, but just for transparency.

In order to avoid your immediate issue, a better workaround instead of installing AWSSDK.Core 3.7.0.10 directly would be to install AWSSDK.QLDBSession directly, with a version that matches AWSSDK.XRay.
